### ISSUE TITLE
Wrong username response when mapping multiple users to a single roleARN

### ISSUE THREAD

**Issue by maorfr** [kubernetes-sigs/aws-iam-authenticator#102]
Hello,
First of all - thank you for this tool!

When using the below configuration and running an unauthorized command - the returned user is incorrect. The returned username is always the last one in the ConfigMap.

Thanks in advance!

ConfigMap:
```
apiVersion: v1
data:
  config.yaml: |
    clusterID: dev.example.com
    server:
      mapRoles:
      - roleARN: arn:aws:iam::11111111111111:role/k8s-dev-developers-access
        username: developer1
        groups:
        - developers
      - roleARN: arn:aws:iam::11111111111111:role/k8s-dev-developers-access
        username: developer2
        groups:
        - developers
      - roleARN: arn:aws:iam::11111111111111:role/k8s-dev-developers-access
        username: awesome-developer
        groups:
        - developers
kind: ConfigMap
metadata:
  labels:
    app: heptio-authenticator-aws
  name: cluster-auth-config
  namespace: kube-system
```
Role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developers
  namespace: dev
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  - pods
  - pods/log
  - pods/exec
  - pods/portforward
  - services
  - secrets
  - ingresses
  - configmaps
  verbs:
  - '*'
```
RoleBinding:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developers-binding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developers
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: developers
```
Command (using credentials of developer1):
`kubectl get cronjob`
Response:
`Error from server (Forbidden): cronjobs.batch is forbidden: User "awesome-developer" cannot list cronjobs.batch in the namespace "dev"`
