### ISSUE TITLE
kubectl works but helm client doesn't work

### ISSUE THREAD

**Issue by so0k** [kubernetes-sigs/aws-iam-authenticator#106]
I'm having `Unauthorized` errors using `stern`/`helm` which I don't have without heptio-authenticator-aws (using basic auth / client cert in kubeconfig instead of user exec).

```
kube-apiserver-ip-....internal kube-apiserver        1 wrap.go:42] GET /api/v1/namespaces/kube-system/pods?watch=true: (70.261µs) 401 [[stern/v1.8.1+$Format:%h$ (darwin/amd64) kubernetes/$Format] 10.51.2.100:20724]
kube-apiserver-ip-....internal kube-apiserver        1 wrap.go:42] GET /api/v1/namespaces/kube-system/pods?watch=true: (113.347µs) 401 [[stern/v1.8.1+$Format:%h$ (darwin/amd64) kubernetes/$Format] 10.51.10.177:36914]
kube-apiserver-ip-....internal kube-apiserver        1 wrap.go:42] GET /api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: (151.714µs) 401 [[helm/v0.0.0 (darwin/amd64) kubernetes/$Format] 10.51.10.177:64346]
```

Authenticator server configuration:
```
      mapRoles:
      # statically map arn:aws:iam::000000000000:role/KubernetesAdmin to a cluster admin
      - roleARN: ${admin_role_arn}
        username: kubernetes-admin
        groups:
        - system:masters
```

`system:masters` group is bound to cluster-admin clusterRole:

```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:masters
```

which has full access:
```rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```

through kubectl I can get/watch pods in kube-system namespace
but using `helm` client, it is unable to list the pods in kube-system namespace

are the tokens somehow signed for kubectl only?

## Versions

- kubectl: reproduced on both kubectl 1.9 and 1.10.4 clients - server is 1.9.4
- helm: 2.8.2
- stern: 1.6.0
