### ISSUE TITLE
Tilde ~ not parsed correctly - executable file not found in $PATH

### ISSUE THREAD

**Issue by ripper234** [kubernetes-sigs/aws-iam-authenticator#136]
A fresh install. I first installed aws-iam-authenticator via `go get`, removed it, and then installed the aws provisioned.

aws-iam-authenticator help
```
A tool to authenticate to Kubernetes using AWS IAM credentials

Usage:
  aws-iam-authenticator [command]

Available Commands:
  help        Help about any command
  init        Pre-generate certificate, private key, and kubeconfig files for the server.
  server      Run a webhook validation server suitable that validates tokens using AWS IAM
  token       Authenticate using AWS IAM and get token for Kubernetes
  verify      Verify a token for debugging purpose
  version     Version will output the current build information

Flags:
  -i, --cluster-id ID       Specify the cluster ID, a unique-per-cluster identifier for your aws-iam-authenticator installation.
  -c, --config filename     Load configuration from filename
  -h, --help                help for aws-iam-authenticator
  -l, --log-format string   Specify log format to use when logging to stderr [text or json] (default "text")

Use "aws-iam-authenticator [command] --help" for more information about a command.
```

cat ~/.kube/config-test
```
apiVersion: v1
clusters:
- cluster:
    server: <MY_URL>        (I actually entered my server details here)
    certificate-authority-data:       (redacted)
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "test"
        # - "-r"
        # - "<role-arn>"
      # env:
        # - name: AWS_PROFILE
        #   value: "<aws-profile>"
```

kubectl get svc -v=8

```
I0820 07:36:08.962688    6349 loader.go:357] Config loaded from file /Users/admin/.kube/config-test
I0820 07:36:08.963331    6349 round_trippers.go:383] GET <MY_URL>
I0820 07:36:08.963342    6349 round_trippers.go:390] Request Headers:
I0820 07:36:08.963366    6349 round_trippers.go:393]     Accept: application/json, */*
I0820 07:36:08.963373    6349 round_trippers.go:393]     User-Agent: kubectl/v1.10.3 (darwin/amd64) kubernetes/2bba012
I0820 07:36:08.963571    6349 round_trippers.go:408] Response Status:  in 0 milliseconds
I0820 07:36:08.963580    6349 round_trippers.go:411] Response Headers:
I0820 07:36:08.963627    6349 cached_discovery.go:124] skipped caching discovery info due to Get <MY_URL>: getting token: exec: exec: "aws-iam-authenticator": executable file not found in $PATH
I0820 07:36:08.963668    6349 round_trippers.go:383] GET <MY_URL>
I0820 07:36:08.963677    6349 round_trippers.go:390] Request Headers:
I0820 07:36:08.963684    6349 round_trippers.go:393]     User-Agent: kubectl/v1.10.3 (darwin/amd64) kubernetes/2bba012
I0820 07:36:08.963691    6349 round_trippers.go:393]     Accept: application/json, */*
I0820 07:36:08.963787    6349 round_trippers.go:408] Response Status:  in 0 milliseconds
I0820 07:36:08.963795    6349 round_trippers.go:411] Response Headers:
I0820 07:36:08.963808    6349 cached_discovery.go:124] skipped caching discovery info due to Get <MY_URL>: getting token: exec: exec: "aws-iam-authenticator": executable file not found in $PATH
I0820 07:36:08.963994    6349 round_trippers.go:383] GET <MY_URL>
I0820 07:36:08.964002    6349 round_trippers.go:390] Request Headers:
I0820 07:36:08.964023    6349 round_trippers.go:393]     Accept: application/json, */*
I0820 07:36:08.964028    6349 round_trippers.go:393]     User-Agent: kubectl/v1.10.3 (darwin/amd64) kubernetes/2bba012
I0820 07:36:08.964106    6349 round_trippers.go:408] Response Status:  in 0 milliseconds
I0820 07:36:08.964115    6349 round_trippers.go:411] Response Headers:
I0820 07:36:08.964130    6349 cached_discovery.go:124] skipped caching discovery info due to Get <MY_URL>: getting token: exec: exec: "aws-iam-authenticator": executable file not found in $PATH
I0820 07:36:08.964154    6349 factory_object_mapping.go:93] Unable to retrieve API resources, falling back to hardcoded types: Get <MY_URL>: getting token: exec: exec: "aws-iam-authenticator": executable file not found in $PATH
F0820 07:36:08.964287    6349 helpers.go:119] error: the server doesn't have a resource type "svc"
