### ISSUE TITLE
kubectl using aws-iam-authenticator fails for MFA required by policy users 

### ISSUE THREAD

**Issue by StevenACoffman** [kubernetes-sigs/aws-iam-authenticator#146]
While I can get a token, I am not able to use kubectl commands using the aws-iam-authenticator since my policy requires me to use mfa for all assumed roles.

Account number redacted below.
I am using kubectl 1.10.5 with an AWS EKS cluster. I re-installed aws-iam-authenticator like this today:
```
go get -u -v github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator
```
I have my `~/.aws/config` file with these profiles:
```
[profile read-only]
region=us-east-1
output=json

[profile admin]
source_profile = read-only
role_arn = arn:aws:iam::<aws_account>:role/admin-access
mfa_serial = arn:aws:iam::<aws_account>:mfa/scoffman
```
The `role/admin-access` has a trust policy attached requiring MFA for sts assume:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::<aws_account>:root"
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "Bool": {
          "aws:MultiFactorAuthPresent": "true"
        },
        "NumericLessThan": {
          "aws:MultiFactorAuthAge": "14400"
        }
      }
    }
  ]
}
```

I can sts assume the admin-access role fine with my mfa using:
```
$ aws sts assume-role --role-arn arn:aws:iam::<aws_account>:role/admin-access --role-session-name my-dumb-session-name --profile full
```
After launching a fresh EKS cluster I did `kubectl edit -n kube-system configmap/aws-auth` and added the iam role to the `mapRoles` section with a rolearn, username, and groups like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <ARN>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::<aws_account>:role/admin-access
      username: admin:{{AccountID}}:{{SessionName}}
      groups:
          - system:masters
```
However, I get in an endless loop of mfa when my `kubeconfig` file has this (note the commented out role args):
```
apiVersion: v1
clusters:
- cluster:
    server: <endpointurl>
    certificate-authority-data: <base64encodedcacert>
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "<cluster-name>"
        #- "-r"
        #- "arn:aws:iam::<aws_account>:role/admin-access"
      env:
        - name: AWS_PROFILE
          value: "admin"
```

However, it will not use mfa when it attempts to sts assume role if I adjust the template ending portion like this:
```
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "<cluster-name>"
        - "-r"
        - "arn:aws:iam::<aws_account>:role/admin-access"
    # env:
    #    - name: AWS_PROFILE
    #      value: "admin"
```
This fails with an error `is not authorized to perform: sts:AssumeRole on resource` because no mfa was supplied with the sts assume role call.

However, I can execute the command:
```
export AWS_PROFILE=admin; aws-iam-authenticator token -i <cluster-name>
```
And get a seemingly successful result with a single MFA entered. The output looks like this (token partially redacted):
```
{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1alpha1","spec":{},"status":{"token":"k8s-aws-v1.XXXXXXXX"}}
```

**Comment by StevenACoffman** [comment]
```
$ aws-iam-authenticator token -i <cluster-name> -r 'arn:aws:iam::<aws_account>:role/admin-access' 
could not get token: AccessDenied: User: arn:aws:iam::<aws_account>:user/scoffman is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<aws_account>:role/Full
	status code: 403, request id: <requestid>

``` 
Fails if the role has a trust policy that requires mfa, but succeeds for roles without this restriction.

As noted above, a profile that sources another with the mfa specified appears to succeed.
```
$ export AWS_PROFILE=admin; aws-iam-authenticator token -i <cluster-name>
```

**Comment by StevenACoffman** [comment]
So this works fine as in my last comment, but my initial effort had bad indentation in the `aws-auth` configmap which lead to the MFA infinite loop. This is the corrected version for anyone else:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <ARN>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::<aws_account>:role/admin-access
      username: admin:{{AccountID}}:{{SessionName}}
      groups:
        - system:masters
```
