### ISSUE TITLE
EKS Connections using role switching with MFA ask everytime for MFA token

### ISSUE THREAD

**Issue by daraacca** [kubernetes-sigs/aws-iam-authenticator#151]
I wish to connect to an EKS Instance using kubectl with the authenticator. To connect to this instance I want to assume a role in the necessary AWS Account where EKS Lives.    The config map of the EKS Instance has also been updated to specify the same role -

I have the following kube config 

```
apiVersion: v1
clusters:
- cluster:
    server: https://xxxxxxx.sk1.us-east-1.eks.amazonaws.com
    certificate-authority-data: xxxxxxxxxxxxxxx
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      env:
      - name: "AWS_PROFILE"
        value: "playground-power-user"
      args:
        - "token"
        - "-i"
        - "test-cluster"
```

my AWS config file is as follows

```
[profile playground-power-user]
region = us-east-1
source_profile = main
role_arn = arn:aws:iam::12345678:role/power-user
mfa_serial = arn:aws:iam::112233445566:mfa/user@company.com
```

my aws-auth-cm.yaml  config map is as follows

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::12345678:role/eks-cluster-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::12345678:role/power-user
      username: admin:{{AccountID}}:{{SessionName}}
      groups:
        - system:masters
```

This is all good. When i connect to EKS, I am asked for my MFA token, which is accepted and command is executed

>> kubectl get clusterrolebindings
Assume Role MFA token code: 275230
NAME                                                   AGE
aws-node                                               7d
cluster-admin                                          7d
eks:kube-proxy                                         7d
eks:node-bootstrapper                                  7d

HOWEVER, for every kubectl command, I have to give the MFA token again.  This is obviously unworkable. Any ideas to avoid this???

**Comment by jukkafor** [comment]
I'm facing this issue as well and it is hugely annoying. While waiting for caching to be implemented into aws-iam-authenticator I made a small Bash wrapper script for caching the output of this command.

**Comment by daraacca** [comment]
Hi Jukka, that sounds really interesting. Would you have an example of such a bash script??

**Comment by 3r1co** [comment]
Hi @jukkafor , do you mind sharing this bash wrapper? I did not find the wrapper mentioned by @daraacca  here :( This issue is really annoying for us

**Comment by extron-cloudops** [comment]
Hi @3r1co - i found the script in a separate issue. I repost it here -

`
#!/usr/bin/env bash
# Only tested on OS X
CACHE_FILE=${HOME}/.kube/heptio-authenticator-${AWS_PROFILE}.cache
MAXTIME=800
if [ -f $CACHE_FILE ]; then
    TS_DB=$(stat -t "%s" ${CACHE_FILE} | cut -d' ' -f10 | tr -d '"')
    AGE=$(( `date +%s` - $TS_DB ))
    if [[ $AGE -le $MAXTIME ]]; then
        cat ${CACHE_FILE}
    else
        heptio-authenticator-aws "$@" | tee $CACHE_FILE
    fi
else
    heptio-authenticator-aws "$@" | tee $CACHE_FILE
fi
`

**Comment by Martin-Andersen** [comment]
@daraacca how do you use the script?

**Comment by bgora** [comment]
@daraacca 

when I use the wrapper script in my kubeconfig I get 

``` 
No resources found.
Unable to connect to the server: getting credentials: exec: fork/exec /Users/bgirsch/bin/aws-iam-authenticator-wrapper: exec format error
```

kubectl 1.11.6

**Comment by tbekas** [comment]
@bgora @mazzy89  add this to the beginning of the file. Works for me on kubectl v1.13.1
```
#!/bin/bash
```

**Comment by danbudris** [comment]
What is the MFA configuration for the `IAM role` that is being used?  You can require MFA for every connection, which is a simple bool condition specifying that MFA is set (in the IAM role confirugation JSON):
`"Condition": {"Bool": {"aws:MultiFactorAuthPresent": "true"}}`

This will in fact prompt you for the auth token on every cal.  An alternative is to set a condition in the IAM role which ensures that the MFA token is less than a certain age, and only prompt for it if it's greater, like so:
`"Condition": {"NumericGreaterThanIfExists": {"aws:MultiFactorAuthAge": "3600"}}`

[See this link for more information on MFA Conditionals for IAM Roles.](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_sample-policies.html#ExampleMFADenyNotRecent)

**Comment by jtstrohl** [comment]
Workaround suggested above is helpful, but still a pain, especially if you have users with workstations on multiple platforms (windows, mac, linux, etc.).  We are left having to access our clusters using individual IAM user credentials instead of roles, which means we have to manage individual user access to each cluster.  This is also quickly becoming unsustainable.

This is THE tool for authenticating to EKS via IAM permissions and MFA is AWS best practices, so if we want to use EKS the right way, we are forced into this issue.

Is there an ETA on a fix for this issue?

**Comment by daraacca** [comment]
Hi all - i found a better way than using the wrapper workaround..  I have been using AWS-VAULT ( which is available for Linux, Max & Windows ) as a credentials store.. This stores the temp credentials which can then be re-used by the authenticator..  You can find it here https://github.com/99designs/aws-vault

**Comment by jtstrohl** [comment]
Thanks @daraacca for posting an update with your improved workaround!  I appreciate it.  We will take a look.

**Comment by mazzy89** [comment]
For me it does not work that workaround with `aws-vault`

```yaml
- name: mycluster--aws-auth
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
        - token
        - -i
        - voyager.staging.productboard.net
      command: aws-vault exec kubernetes-admin -- aws-iam-authenticator
```

when I try to run a command like this:

```sh
Unable to connect to the server: getting token: exec: exec: "aws-vault exec kubernetes-admin -- aws-iam-authenticator": executable file not found in $PATH
```
