### ISSUE TITLE
Is it possible to use with AssumeRoleWithWebIdentity?

### ISSUE THREAD

**Issue by cromega** [kubernetes-sigs/aws-iam-authenticator#154]
It's not an issue per se because I'm not even sure what I'm trying to do is possible.

I installed an EKS cluster but a requirement is setting up federated login with G-suite. I created a Role for federated access via the Google identity provider:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "accounts.google.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "accounts.google.com:aud": "FOO-BAR.apps.googleusercontent.com"
        }
      }
    }
  ]
}
```

The aws-auth-cm.yml applied on the cluster looks like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
 name: aws-auth
 namespace: kube-system
data:
 mapRoles: |
   - rolearn: <ARN of the role above>
     username: kubernetes-admin
     groups:
       - system:masters
```

and my kubeconfig is as follows:

```
users:
- name: aws
 user:
   exec:
     apiVersion: client.authentication.k8s.io/v1alpha1
     command: aws-iam-authenticator
     args:
       - "token"
       - "-i"
       - "eks-test"
       - "-r"
       - "<ARN of the role above>"
```

If I execute aws-iam-authenticator directly with the same parameters I get 
```
could not get  token: AccessDenied: Access denied
```

I'm not quite sure what I'm trying to do makes sense but let me explain what I expect the user experience to look like:

```
$ kubectl --kubeconfig ~/.kube/eks get svc
Log in  to your account following this URL and paste the authentication code in here:
https://accounts.google.com/o/auth2/auth?client_id=....
code: asddfsfq343j2kl2k4

Temporary access granted for 3600 seconds.
```

Is it possible to set up authentication like this? If not then I don't really understand how the authenticator is supposed to get a token through normal AssumeRole.

Please help!
