### ISSUE TITLE
Question/Help

### ISSUE THREAD

**Issue by hollowimage** [kubernetes-sigs/aws-iam-authenticator#172]
I am having issues with being able to restrict access to a smaller permission set while using the authenticator (kops aws cluster).

It seems no matter what the mapping looks like, for instance:
```
      - roleARN: arn:aws:iam::00000000000:role/ROLE1
        username: user1:{{SessionName}}
        groups:
        - readonly
```

i seem to be able to execute any command against the cluster. 

What really confuses me is that i can add any group up there, it doesnt matter if the group subject definition exists or not. 

I can even remove groups: bit entirely, and the username that gets passed into the cluster, gets full access rights.

I have kicked the ds pod over many times, changed the configs, but it doesnt matter.  I seem to have full access.

(cluster)role and (cluster)rolebinding exists or not, doesn't matter. 

```
      - roleARN: arn:aws:iam::00000000000:role/ROLE1
        username: user1:{{SessionName}}
```
this is identical to
```
      - roleARN: arn:aws:iam::00000000000:role/ROLE1
        username: ranomletters123
```
and etc.

Am i missing a step somewhere?
