### ISSUE TITLE
Bad string interpolation in aws-iam-authenticator.kubeconfig file

### ISSUE THREAD

**Issue by chrisghill** [kubernetes-sigs/aws-iam-authenticator#177]
This could certainly be an issue with my configuration or usage since I don't see this issue mentioned elsewhere.  Basically when I run:
`aws-iam-authenticator init -i clustername`
It generates the config file, but the server field is invalid.  Here it is:
```
# clusters refers to the remote service.
clusters:
  - name: aws-iam-authenticator
    cluster:
      certificate-authority-data: <certificate>
      server: https://%!d(string=localhost):21362/authenticate
# users refers to the API Server's webhook configuration
# (we don't need to authenticate the API server).
users:
  - name: apiserver
# kubeconfig files require a context. Provide one for the API Server.
current-context: webhook
contexts:
- name: webhook
  context:
    cluster: aws-iam-authenticator
    user: apiserver
```
It seems it isn't interpolating the string correctly.  When I try to create a cluster or perform a rolling update on an existing cluster, the kube-apiserver logs complain:
`invalid authentication config: parse http://https://%!d(string=localhost):21362/authenticate: invalid URL escape "%!d"`
And the cluster never goes healthy.

I've tried passing in the flag --hostname, like this:
`aws-iam-authenticator init -i clustername --hostname "127.0.0.1"`
But the generated file is still invalid:
```
# clusters refers to the remote service.
clusters:
  - name: aws-iam-authenticator
    cluster:
      certificate-authority-data: <certificate>
      server: https://%!d(string=127.0.0.1):21362/authenticate
# users refers to the API Server's webhook configuration
# (we don't need to authenticate the API server).
users:
  - name: apiserver
# kubeconfig files require a context. Provide one for the API Server.
current-context: webhook
contexts:
- name: webhook
  context:
    cluster: aws-iam-authenticator
    user: apiserver
```

Obviously I could overwrite this field with `127.0.0.1` manually after its generated, but I'm trying to automate the process.  Any help would be appreciated.

Edit: Also, I'm running the most recent version of this repo, as I just ran:
`go get github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator`
And my go version is 1.11.2:
`go version go1.11.2 linux/amd64`
