### ISSUE TITLE
error: You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by pkelleratwork** [kubernetes-sigs/aws-iam-authenticator#179]
need help asap - trying to replace prod cluster - cannot connect to cluster via circleci (user circleci)
verified aws-iam-authenticatior is working
kubectl can change context to cluster
ran `kubectl edit -n kube-system configmap/aws-auth` and added user to list
ran `kubectl create clusterrolebinding circleci-cluster-admin-binding --clusterrole=cluster-admin --user=circlci` for user
test with
```
+ kubectl get pods
error: You must be logged in to the server (Unauthorized)
```

I can connect to cluster from my box, where i made it from. i have referred with no luck to 
https://stackoverflow.com/questions/50791303/kubectl-error-you-must-be-logged-in-to-the-server-unauthorized-when-accessing?rq=1
https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/105

**Comment by pkelleratwork** [comment]
context
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: redacted
    server: https://nnnnnn.sk1.us-east-2.eks.amazonaws.com
  name: arn:aws:nnnnnnnnnn:cluster/dev
contexts:
- context:
    cluster: arn:aws:eks:nnnnnnnnn:cluster/dev
    user: arn:aws:eks:nnnnnnnnnn:cluster/dev
  name: arn:aws:eksnnnnnnnnnn:cluster/dev
current-context: arn:aws:eks:nnnnnnnn:cluster/dev
kind: Config
preferences: {}
users:
- name: arn:aws:eks:nnnnnnnnnn:cluster/dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - arn:aws:eks:nnnnnnnn:cluster/dev
      command: aws-iam-authenticator
      env:
        - name: AWS_PROFILE
          value: "circleci"
```
