### ISSUE TITLE
Automatically generating and then mapping roles

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-sigs/aws-iam-authenticator#18]
@mattmoyer Hi, thanks as always for maintaining the great project 👍 

Would you mind if I've suggested one more feature to this?

So - assuming we had 100 or more K8S cluster users authenticated via SAML + AWS IAM, I'd like to provide every authenticated user a full access to his/her "playground" namespace by default.

The motivation is that to encourage every developer in a relatively large organization to experiment & learn against a real cluster without asking admin(s) for a k8s credential and/or namespaces, permissions to play with.

I'm assuming that manually creating a role per authenticated user wouldn't be an ideal solution here because we had assumed 100 or more potential cluster users.

Even though I'm not yet sure if it fits within the scope of kubernetes-aws-authenticator, I have no concrete solutions in my mind other than doing it in kubernetes-aws-authenticator.

Anyway, the its configuration to achieve the idea would look:

```yaml
     # map federated users in my "Developer" role to users like
      # "developer:alice-example.com". The SessionName is an arbitrary role name
      # like an e-mail address passed by the identity provider. Note that if this
      # role is assumed directly by an IAM User (not via federation), the user
      # can control the SessionName.
      - roleARN: arn:aws:iam::000000000000:role/Developer
        username: developer:{{SessionName}}
        groups:
        - template: |
            kind: Role
            apiVersion: rbac.authorization.k8s.io/v1alpha1
            metadata:
              namespace: {{SessionName}}-playground
              name: {{SessionName}}-playground-admin
            rules:
              - apiGroups: ["*"]
                resources: ["*"]
                verbs: ["*"]
```

**Comment by mumoshu** [comment]
@mattmoyer Otherwise, would it be nicer to allow one to setup a WebHook from kubernetes-aws-authenticator to an another webapp so that the app can react to any successful authentication by e.g. creating a bespoke k8s role for the newly authenticated user?

**Comment by mattmoyer** [comment]
Hi @mumoshu, sorry for the slow response on this. I think it's an interesting idea, but I'd like to find a way to enable it with another controller/daemon vs. building it into this code if possible.

A webhook could work, or maybe a CRD type like `AWSPrincipal` that the authenticator would create in response to successful authentications? Then you could write a controller loop that reacted to new principals by creating namespaces or role bindings, etc...

**Comment by mumoshu** [comment]
Hh ＠mattmoyer!

I agree we'd want an another controller for it.

Regarding a dedicated CRD type - good idea! I prefer it rather than webhooks, so that kubernetes-aws-authenticator can reliably communicate with other controller(s), via CRDs, without duplicating webhook call for each consumer, retrying when transient failure on consumers, etc.

Would you mind providing me any idea and/or possible reference, prototype about the the AWSPrincipal type(especially its fields) look like?
Perhaps I can submit a PR if the direction is given.

**Comment by mattmoyer** [comment]
Sure, maybe something like:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awsprincipals.authenticator.heptio.com
spec:
  group: authenticator.heptio.com
  version: v1
  scope: Cluster
  names:
    plural: awsprincipals
    singular: awsprincipal
    kind: AWSPrincipal
```

An instance of the CRD would look something like:
```yaml
apiVersion: authenticator.heptio.com/v1
kind: AWSPrincipal
metadata:
  # resource name specified in configuration, sanitized to be a valid k8s name
  name: federated-user-mattmoyer-abcdef

  # labels and annotations specified in configuration
  labels:
    my-aws-account-label: "000000000000"
    my-aws-role: KubernetesAdmin
  annotations:
    mycontroller.example.com/provisionNamespace: mattmoyer-dev-environment
spec:
  # most recent authenticated ARN, account ID, user ID, and session name
  arn: "arn:aws:iam::000000000000:role/KubernetesAdmin"
  accountID: "000000000000"
  userID: "AROAAAAAAAAAAAAAAAAAA"
  sessionName: "mattmoyer"

  # most recent final username and groups generated by kubernetes-aws-authenticator
  username: mattmoyer
  groups:
   - cluster:admin
   - aws:user
status:
  # time of most recent authentication
  lastAuthenticated: 2017-11-21T14:51:30.986260
```

We might configure this with a new sub-section of `mapRoles` like:
```yaml
# [...]
     mapRoles:
      - roleARN: arn:aws:iam::000000000000:role/KubernetesAdmin
        username: admin:{{SessionName}}
        groups:
        - system:masters

        # new key to specify publishing a CRD when users log in under this role
        publishCRD:
          # a template for the name of the resource
          name: federated-user-{{SessionName}}

          # some labels to set on the CRD
          # (for example, these might get copied to the namespaces generated by the controller)
          labels:
            my-aws-account-label: "000000000000"
            my-aws-role: KubernetesAdmin

          # some annotations to set on the CRD, for example to signal another controller to act on it
          annotations:
            mycontroller.example.com/provisionNamespace: "{{SessionName}}-dev-environment"
```

In that example,
1. I could log in as federated user `mattmoyer` using the current `mapRoles` functionality.
1. The kubenetes-aws-authenticator would create an AWSPrincipal CRD `federated-user-mattmoyer-abcdef`
1. The CRD would be annotated with `mycontroller.example.com/provisionNamespace=mattmoyer-dev-environment"`.
1. The "dev namespace provisioner" controller could see that CRD and create a `mattmoyer-dev-environment` namespace and role binding.
1. My session would almost immediately have access to a dev namespace.

I think the kubenetes-aws-authenticator code would only ever create the CRD, so it would be up to an administrator (or some other controller) to clean up stale entries.
