### ISSUE TITLE
How do you troubleshoot error: You must be logged in to the server (Unauthorized)?

### ISSUE THREAD

**Issue by holyjak** [kubernetes-sigs/aws-iam-authenticator#190]
Hello, I would very much appreciate tips on how to troubleshoot

> How do you troubleshoot error: You must be logged in to the server (Unauthorized)

## Facts

1. `kubectl get svc` fails with `error: You must be logged in to the server (Unauthorized)`
2. `aws-iam-authenticator token -i mycluster` returns a token so the communication with IAM seems to be OK; the error is somewhere later in the process
3. Other users, with other IAM roles, can access the cluster without a problem so it is something with this particular (assumed) role. The role is "readonly" in AWS but I guess that should be good enough for connecting to the cluster.
4. I have added the role to kubernetes' `aws-auth` and applied it (see below); though it would be awesome if the tool provided a more helpful error message if I fail to do so (or at least a way to check that it works as intended)

```yaml
# aws-auth.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::123456:role/admin
      username: system:node:{{SessionName}}
      groups:
      - system:masters
    - rolearn: arn:aws:iam::123456:role/readonly
      username: system:node:{{SessionName}}
      groups:
      - db-user
      - system:masters

  mapUsers: |

  mapAccounts: |
      - "555555"
```
Applied with `kubectl apply -f aws-auth.yaml`. 

NOTE: We use a "jump account" for all users and only after authenticating with it, we assume a role in the target account containing kubernetes. This works just fine for the "admin" role but, as described, fails for the "readonly" role.

`kubeconfig`:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: redacted...
    server: https://228DD8BE5749AB4552832A0869A1921B.yl4.eu-west-1.eks.amazonaws.com
  name: mycluster
contexts:
- context:
    cluster: mycluster
    namespace: common
    user: mycluster
  name: mycluster
current-context: mycluster
kind: Config
preferences: {}
users:
- name: mycluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - mycluster
      command: aws-iam-authenticator
      env: null
```

User info:

```
 aws sts get-caller-identity
{
    "UserId": "AAAAA:john.doe@777777",
    "Account": "123456",
    "Arn": "arn:aws:sts::123456:assumed-role/readonly/john.doe@7777773"
}
```

Thank you!
