### ISSUE TITLE
Each kube config user is locked to a single Kubernetes cluster

### ISSUE THREAD

**Issue by jutley** [kubernetes-sigs/aws-iam-authenticator#196]
The README for this project includes this sample `.kube/config` snippet.

```
users:
- name: kubernetes-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "CLUSTER_ID"
        - "-r"
        - "ROLE_ARN"
  # no client certificate/key needed here!
```

My understanding is that this user will only be valid for the cluster configured to use `CLUSTER_ID`. We can create a user per-cluster, but this creates a lot of redundant configuration.

Is there a better way to use `aws-iam-authenticator` with many clusters? Or is it absolutely necessary to create one user per-cluster?
