### ISSUE TITLE
MFA maprole has to be lower case

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-iam-authenticator#220]
/bug
### What happened?
Created a aws-auth ConfigMap with MFA mapRole:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: aws-iam-authenticator
  labels:
    k8s-app: aws-iam-authenticator
data:
  config.yaml: |
    # a unique-per-cluster identifier to prevent replay attacks
    # (good choices are a random token or a domain name that will be unique to your cluster)
    clusterID: my-dev-cluster.example.com
    server:
      # each mapRoles entry maps an IAM role to a username and set of groups
      # Each username and group can optionally contain template parameters:
      #  1) "{{AccountID}}" is the 12 digit AWS ID.
      #  2) "{{SessionName}}" is the role session name.
      mapRoles:
      - roleARN: arn:aws:iam::000000000000:role/CrossAccountMFA
        username: kubernetes-admin
        groups:
        - system:masters
```
When the role actual name is `arn:aws:iam::000000000000:role/CrossAccountMFA`
Got error:
```
time="2019-04-18T22:53:05Z" level=warning msg="access denied" arn="arn:aws:iam::000000000000:role/CrossAccountMFA" client="127.0.0.1:42236" error="ARN is not mapped: arn:aws:iam::000000000000:role/crossaccountmfa" method=POST path=/authenticate
```

### What should happen?
Role Map looks up should use exact match since IAM role is case sensitive. See [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_roles.html#troubleshoot_roles_cant-assume-role)
