### ISSUE TITLE
Question : How to pass {{SessionName}} to RoleBinding

### ISSUE THREAD

**Issue by anshrma** [kubernetes-sigs/aws-iam-authenticator#225]
In kubconfig , a developer assumes the role developer_role

```
- -r
- arn:aws:iam::123456789012:role/developer_role
```

In EKS aws-auth configmap, admin adds {{SessionName}} , which gives me relevant session details combining user.username section and user.uid section in audit logs 

```

- rolearn: arn:aws:iam::123456789012:role/developer_role
  username: myapp-developer:{{SessionName}}
  groups:
    - admin

```

Then a cluster admin binds the admin K8 inbuilt userfacing customer role to the username created above

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-namespace
  namespace: my-namespace
subjects:
  - kind: User
    name: myapp-developer:{{SessionName}}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
```

Developer, when they assume the developer_role, get access denied just to list any pods as well. 
When the cluster admin removes {{SessionName}} from aws-auth config map as well as from role binding, it works good.

Where am i going wrong ?

**Comment by nckturner** [comment]
Did your RoleBinding actually have `{{SessionName}}` in it?  Or did you substitute it with the actual session name that the assuming user passed to assume-role?

**Comment by bdashrad** [comment]
I'm having the same issue. Are you on EKS? Is it possible aws is not running a compatible version on the control plane?

**Comment by anshrma** [comment]
@bdashrad / @nckturner - I ended up with following to address the needs. My goal is to use user facing role that is provided by K8 and use RoleBinding, so that i dont end up writing additional permissions for admin, edit and view on namespaces.

```
- rolearn: arn:aws:iam::123456789012:role/developer_role
  username: myapp-developer:{{SessionName}}
  groups:
    - developer-group
```

Then used rolebinding to bind this group to admin user facing K8 role

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-namespace
  namespace: my-namespace
subjects:
  - kind: Group
    name: developer-group
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
```
