### ISSUE TITLE
Support for assumed role ARNs

### ISSUE THREAD

**Issue by JacobHenner** [kubernetes-sigs/aws-iam-authenticator#229]
Hello,

Are there any plans to support assumed-role ARNs for authentication?

Right now, both IAM role and IAM user ARNs are supported, but not STS assumed role ARNs. 

This would be helpful, as it would allow maintainers to provision access not just by role (which may map to many users), but by role **and** username (as the name of the role session).

For example, instead of:
arn:aws:iam::account-id:role/role-name

Support:
arn:aws:sts::account-id:assumed-role/role-name/role-session-name

Thanks

**Comment by casey-robertson** [comment]
This is our auth model (brand new to AWS/EKS)... yeah, not having assumed role support is going to be a deal breaker.

**Comment by nckturner** [comment]
You can currently only map each role to a username and set of groups, but you can pass the session name into Kubernetes as the username and create an RBAC role binding there per session name, if you need different permissions per session name.  

```
  - roleARN: arn:aws:iam::123456789012:role/Admin
    username: admin:{{SessionName}}
    groups:
    - system:masters
```

If the session name is `bar`, then:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: foo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin:bar
```

Does that work for you?
