### ISSUE TITLE
How does a cross account user updating the kubeconfig without assuming a role from EKS cluster account?

### ISSUE THREAD

**Issue by tomqwu** [kubernetes-sigs/aws-iam-authenticator#235]
e.g. let's say the EKS cluster is in 000000000000, I have an admin user in 12343456789012, how does alice user can run this aws-iam-authenticator command to update the kubeconfig? Similarly, how mapRole work in this case without using assuming a role in 000000000000 account? 

```
  # each mapUsers entry maps an IAM role to a static username and set of groups
  mapUsers:
  # map user IAM user Alice in 12343456789012 to user "alice" in group "system:masters"
  - userARN: arn:aws:iam::12343456789012:user/Alice
    username: alice
    groups:
    - system:masters
```
