### ISSUE TITLE
Feature request: Map IAM Username to ServiceAccount

### ISSUE THREAD

**Issue by mr-karan** [kubernetes-sigs/aws-iam-authenticator#241]
The current Config provides a way to map IAM username to a list of group names in Kubernetes post authentication webhook. Can an option to map the username to a list of service accounts be also given? 

Something like this should work, if implemented (doesn't work as of now):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::<redacted>:user/<redacted>
      username: <redacted>
      serviceaccounts:
        - <redacted>
```

Would this be a good to have, if not in the current configmap spec, maybe in the new CRD spec?
