### ISSUE TITLE
Include UserId in SessionName

### ISSUE THREAD

**Issue by bwagnertrc** [kubernetes-sigs/aws-iam-authenticator#242]
Hi there,

is it possible to include the iam user name in the role session name when assuming a role? This way, k8s api logs would include the original IAM user name in the k8s api logs, along with the session name. Currently, only the session name is included, which appears to be an arbitrary number that needs to be mapped with the AssumeRole events in CloudTrail.

For example, my aws-auth contains the following role mapping:

```
- rolearn: arn:aws:iam::123123123123:role/dev1-role
      username: dev1-{{SessionName}}
      groups:
        - dev1-role
```
This leads to log events with user.username fields like dev1-123456789123456789.
Instead, I suggest session names that session names are set in a way that usernames loke like this dev1-JaneDoe-123456789123456789. This allows to query for all logs where user.username like "-JaneDoe-".

I believe basically this would have to be changed in [token.go](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/pkg/token/token.go)

```
userIDParts := strings.Split(*resp.UserId, ":")
if len(userIDParts) == 2 {
	sessionSetters = append(sessionSetters, func(provider *stscreds.AssumeRoleProvider) {
		provider.RoleSessionName = userIDParts[1]
	})
}
```

**Comment by igtsekov** [comment]
+1

**Comment by ironhalik** [comment]
+1.

Right now, a aws-auth entry like:
```
    - rolearn: arn:aws:iam::xxxx:role/developer-user-role
      username: developer:{{SessionName}}
      groups:
        - developers
```

Produces logs:
```
failed to query namespace "kube-system" from k8s API: namespaces "kube-system" is forbidden: User "developer:EKSGetTokenAuth" cannot get resource "namespaces" in API group "" in the namespace "kube-system"
```
Being able to use more data would be helpful here.
