### ISSUE TITLE
kubectl called from ProcessBuilder failed with AccessDenied

### ISSUE THREAD

**Issue by awouda** [kubernetes-sigs/aws-iam-authenticator#250]
Hi,

We have a buildserver in account 1.
We generate Cloudformation scripts, these are executed by the Java AWS SDK to deploy an EKS cluster on account 2 (our test env). 

Afterwards, we use a scala sys.process.ProcessBuilder to add configs with  kubectl apply.
For instance, set the correct configmap, add secrets, dns stuff etc. 

The calls from this kubectl command from within the (eventually) Java Process fail with:
```
could not get token: AccessDenied: Access denied
 status code: 403, request id: ac4d97b3-ac78-11e9-adb2-2973207678c6
 Unable to connect to the server: getting credentials: exec: exit status 1
```

So, what could be is that the config is wrong, or we assume the wrong role etc.
However; the script programmatically constructed, can be called directly when we SSH to the machine, using the same user of course. And then the script succeeds. I even added a 'source $HOME/.bash_profile' to have other possible related settings propagated to this shell.

This is the script which is generate and executed:
```
#!/bin/bash

echo 'starting script!'

source $HOME/.bash_profile

export AWS_PROFILE=BND-DTA

echo "just exported aws profile to bnd-dta"

echo "AWS PROFILE value: $AWS_PROFILE"

aws sts assume-role --role-arn arn:aws:iam::xxxxxxxxxxx:role/rol-bnd-nl-dta-jenkins  --role-session-name temp_role_for_kubectl

echo "assuming role succeeded"

TOKEN=`aws-iam-authenticator token -i rgn-fon-eks-salesapp `

echo "got token: $TOKEN"

kubectl --kubeconfig /data/jenkins/temp/kube9083319415031772224tmp version
```

It fails on the kubectl command.

the tempfile in the script above has this content:

```
apiVersion: v1
clusters:
- cluster:
    server: https://xxxxxxxxxxxxxxxxx.yl4.eu-west-1.eks.amazonaws.com
    certificate-authority-data:
xS0tl1CxUdJxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1EY3hOekEyTkRJMU1sb1hEVEk1TURjeE5EQTJOREkxTWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGRiCkRnc3puQUdncXErL1FpV09jY3hLSGdKanQvam1TM3EyczRXeHFyNE5uVVVrcyttdzFKMjg5a0JTREo2RDVRRFQKendNRnJLOWFHK2FoWUtPWmxHSlFrK1RmWE9vUlViNkZRY3R3RU8vUXN5cHhKRERVREl6YzN5WXJxQVhsTUpyaAp5czNmbVhBeVo3MjBqSlQrN2NxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdUFpVDhOKzlvcWJjamZkSC84VkE4Ris4d2lybnplNFpsc2x3YVd1Y2JVWEZybTN1ZnVtdUxYdkVndWYKanJzdmhHSGtxQUI1UWxPOC83STg3dFNZcVAwZGNhNzdjcFh1aUVhL0JJMldoazQrQ2FkanBEeTdxZklvdzRsRQp1eU90RGdOV2FPOU1UNEFOTVpjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxgQkFIRjlQRTR3U01NeERsTC8wOW5ZQWU5YU85a0MKUlRGZWxkUmdFTm9DOE1Yano1NzhtbXgzMTJRTTRKdXdMZUlaUDFqUTZreDU5NVYzM2FINmR0R0JtQzZZZnVZcworbm5YV3FQK2xVaCtVMmxWcEMwajBlWHF6VE50Yxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      env:
      - name: "AWS_PROFILE"
        value: "BND-DTA"
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "rgn-fon-eks-salesapp"
        - "-r"
        - "arn:aws:iam::xxxxxxxxxxxxxxxxxx:role/rol-bnd-nl-dta-jenkins"
```

I understood that kubectl uses aws-iam-autheticator to get the token. The token is correctly fetched when calling aws-iam-authenticator directly. I'm overlooking something maybe when calling kubectl from a Java process but cannot find out why. 

If you could be of any help in finding our mistake; greatly appreciated.
