### ISSUE TITLE
--cache issues on Windows

### ISSUE THREAD

**Issue by RMcD** [kubernetes-sigs/aws-iam-authenticator#256]
I'm seeing an issue when using the `--cache` flag from #193 on Windows.

On first run:
```
Cache file C:\Users\mememe\.kube\cache\aws-iam-authenticator\credentials.yaml does not exist.
No cached credential available.  Refreshing...
Assume Role MFA token code: ######
Unable to update credential cache C:\Users\mememe\.kube\cache\aws-iam-authenticator\credentials.yaml: write C:\Users\mememe\.kube\cache\aws-iam-authenticator\credentials.yaml: The process cannot access the file because another process has locked a portion of the file.
```

Then subsequent calls fail with:
```
unable to use cache: cache file C:\Users\mememe\.kube\cache\aws-iam-authenticator\credentials.yaml is not private
```

I've tried adjusting the permissions on the file to be just rw for my user but that doesn't seem to have an effect. I've also tried from different cmd windows with admin and without.

**Comment by RMcD** [comment]
We're currently using a workaround that involved using https://github.com/99designs/aws-vault to manage the MFA authorizations for the aws-iam-authenticator as follows:
```
- name: DevAdmin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - exec
      - DevelopmentAdminAwsProfile
      - --
      - aws-iam-authenticator.exe
      - token
      - -i
      - <eks-clustername>
      - -r
      - arn:aws:iam::<aws-account-id>:role/K8SClusterManagerRole
      command: aws-vault.exe
      env: null
- name: DevRO
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - exec
      - DevelopmentK8sROProfile
      - --
      - aws-iam-authenticator.exe
      - token
      - -i
      - <eks-clustername>
      command: aws-vault.exe
      env: null
```
