### ISSUE TITLE
userarn vs userARN

### ISSUE THREAD

**Issue by lra** [kubernetes-sigs/aws-iam-authenticator#261]
Hi,

We are using both EKS and kops+aws-iam-authenticator on AWS.

I just noticed that in the `aws-auth` configmap of EKS, you need to specify a user arn with `userarn` all lowercase. As specified on https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html
```yaml
  mapUsers: |
    - userarn: arn:aws:iam::555555555555:user/admin
      username: admin
      groups:
        - system:masters
```

But on kops' `aws-iam-authenticator`, you need to specify a user ARN with `userARN`. As is specified on https://github.com/kubernetes-sigs/aws-iam-authenticator#full-configuration-format
```yaml
  mapUsers:
  # map user IAM user Alice in 000000000000 to user "alice" in group "system:masters"
  - userARN: arn:aws:iam::000000000000:user/Alice
    username: alice
    groups:
    - system:masters
```

This is really confusing and hard to debug, especially since everything else is the same (not sure if it was wanted).

Is there a way both could use the same casing?
