### ISSUE TITLE
Issue upgrading from v0.4.0 to v0.5.0

### ISSUE THREAD

**Issue by chinthakagodawita** [kubernetes-sigs/aws-iam-authenticator#288]
Hi,

We're running a kops cluster with a manually installed version of `v0.4.0` which has been working with no issues.

We're attempting an upgrade on to `v0.5.0` (specifically `v0.5.0-alpine-3.7`) with the following server arguments:

```
      - name: aws-iam-authenticator
        image: [...]:v0.5.0-alpine-3.7
        args:
        - server
        - --config=/etc/aws-iam-authenticator/config.yaml
        - --state-dir=/var/aws-iam-authenticator
        - --generate-kubeconfig=/etc/kubernetes/aws-iam-authenticator/kubeconfig.yaml
        # only for kops (https://github.com/goodfoo/aws-iam-authenticator#kops-usage)
        - --kubeconfig-pregenerated=true
        - --backend-mode=ConfigMap,CRD,File
```

I added `backend-mode` flag so that it uses our existing configmap, prior to adding this the daemonset did not log anything past `waiting for informer caches to sync` (logs below).

Post-upgrade, all `kubectl` commands fail with: `error: You must be logged in to the server (Unauthorized)`.

Token verification appears to work, i.e. running:
* `aws-iam-authenticator token -i CLUSTER`
* `aws-iam-authenticator verifiy -i CLUSTER -t TOKEN`

The daemonset's logs have the below, with the final log line repeating:

```
time="2020-02-04T12:24:06Z" level=info msg="creating event broadcaster"
time="2020-02-04T12:24:06Z" level=info msg="setting up event handlers"
time="2020-02-04T12:24:06Z" level=info msg="starting mapper \"ConfigMap\""
time="2020-02-04T12:24:06Z" level=info msg="starting mapper \"CRD\""
time="2020-02-04T12:24:06Z" level=info msg="starting aws iam authenticator controller"
time="2020-02-04T12:24:06Z" level=info msg="waiting for informer caches to sync"
time="2020-02-04T12:24:06Z" level=warning msg="Unable to re-establish watch.  Sleeping for 5 seconds"
time="2020-02-04T12:24:11Z" level=warning msg="Unable to re-establish watch.  Sleeping for 5 seconds"
time="2020-02-04T12:24:16Z" level=warning msg="Unable to re-establish watch.  Sleeping for 5 seconds"
time="2020-02-04T12:24:21Z" level=warning msg="Unable to re-establish watch.  Sleeping for 5 seconds"
time="2020-02-04T12:24:26Z" level=warning msg="Unable to re-establish watch.  Sleeping for 5 seconds"
time="2020-02-04T12:24:31Z" level=warning msg="Unable to re-establish watch.  Sleeping for 5 seconds"
time="2020-02-04T12:24:36Z" level=warning msg="Unable to re-establish watch.  Sleeping for 5 seconds"
time="2020-02-04T12:24:41Z" level=warning msg="Unable to re-establish watch.  Sleeping for 5 seconds" 
```

Are we missing an upgrade step? I've tried regenerating the certs that kops uses and rolling the masters but nothing seems to help.
