### ISSUE TITLE
Credentials not found when used with AWS SSO

### ISSUE THREAD

**Issue by psaffrey-origami** [kubernetes-sigs/aws-iam-authenticator#296]
I want to use `aws-iam-authenticator` to connect to a `k8s` cluster based on AWS IAM integrated with SSO. I connect to AWS based on these instructions:

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html

Having run the `aws configure sso` a browser tab opens and a number of redirects happen. Then I click a button to confirm AWS CLI access, I enter a few more preferences including a profile name and the command finishes. After this, I can successfully run:

    $ aws sts get-caller-identity --profile my-profile-name

to show I am authenticated. However, if I set this profile as my `$AWS_PROFILE` and try to run `aws-iam-authenticator`:

    $ aws-iam-authenticator token -i my-cluster-id
    could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Digging into this in more detail, it looks like the SSO auth process has not produced the usual AWS credentials file in `$HOME/.aws/credentials`. Instead, there is a json file in `$HOME/.aws/cli/cache` that has the usual access ID, secret ID and session token. If I render these as environment variables or into a `credentials` file then my `aws-iam-authenticator` call works fine and I can wire it into my `.kube/config` file to run commands against my cluster. 

I also looked at the underlying [Go SDK methods](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/) and I can't, indeed, see any credentials providers for this type of cache file. Does this mean the problem is upstream in the Go SDK? Shall I raise an issue there?

Superficially, this issue looks similar to some others, but I think these are different:

- https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/141 - but I think this is about third-party credential providers, not those that are generated by native AWS SSO integration
- https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/193 - but I think this is about caching the AWS credential obtained from SSO in exactly the same way the AWS2.0 CLI is currently doing, rather than reading those back for adhoc `kubectl` usage.

Happy to be corrected on any of this - where am I going wrong?

**Comment by romenyrr** [comment]
I'm running across the same issue when using aws-cli (v.2) & aws-iam-auth (v5). It seems that even though the credentials are properly loaded, `export AWS_PROFILE`, by running `aws sts get-caller-identity`, I think there's an issue with the `type` output where it references `sso`. Like you, I was able to extract the creds from `.aws/cli/cache/`and load them as `env` variables and that worked as expected when running `kubectl`. 

```
$ aws configure list                                                                                                                                                                   │···········
      Name                    Value             Type    Location                                                                                                                       │···········
      ----                    -----             ----    --------                                                                                                                       │···········
   profile                  EKSUser           manual    --profile                                                                                                                      │···········
access_key     ****************1234              sso                                                                                                                                   │···········
secret_key     ****************abcd              sso                                                                                                                                   │···········
    region                us-east-1      config-file    ~/.aws/config   
```

I've also tried adjusting my Kube config map to reference the named profile, but no luck there: 

```
apiVersion: v1
clusters:
- cluster:
    server: <endpoint-url>
    certificate-authority-data: <base64-encoded-ca-cert>
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "eks-cluster-name"
        - "-r"
        - "EKS-ADMIN-ROLE:ARN:::::::"
      env:
        - name: AWS_PROFILE
          value: "EKSUser"
```

**Comment by gaffneyd4** [comment]
Great news! AWS SSO Credential Provider support was added to the aws go sdk in version [v1.37.0](https://github.com/aws/aws-sdk-go/pull/3755).

I have opened a PR [in this project](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/360) to update the version of the sdk so that we are able to use SSO credentials with the aws-iam-authenticator.

In my local testing after rebuilding with the updated sdk, SSO credentials are recognized and authentication works as expected.

**Comment by lkskrt** [comment]
I just had the same problem, but @romenyrr's updated comment pointed me in the right direction.

So to make it a bit more clear, as others seem to have the same issue:

What you can do today is completely skip `aws-iam-authenticator` locally and just use AWS CLI v2:

```yaml
users:
- name: my-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
      - eks
      - get-token
      - --cluster-name
      - my-cluster-name
      env:
      - name: AWS_PROFILE
        value: my-sso-profile-name
```
