### ISSUE TITLE
"could not get token" using AWS_PROFILE

### ISSUE THREAD

**Issue by alanbchristie** [kubernetes-sigs/aws-iam-authenticator#307]
Should the `AWS_PROFILE` environment variable work? There's a lot of discussion that it should.

I'm using: -

```
$ aws-iam-authenticator version
{"Version":"v0.5.0","Commit":"1cfe2a90f68381eacd7b6dcfa2bf689e76eb8b4b"}
```

I have a kube config user section like this: -

```
users:
- name: weyyu@im-demo.eu-central-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: weyyu
      args:
      - token
      - -i
      - im-demo
```

and a `~/.aws/credentials` like this: -

```
[weyyu]
aws_acces_key_id=***************
aws_secret_access_key=***************
region=eu-central-1
```

With `AWS_PROFILE=weyyu` all I get is...

```
$ kubectl get no
could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

If, on the other hand, I set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` variables in the kubeconfig the authentication works, i.e. this is OK: -

```
users:
- name: weyyu@im-demo.eu-central-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      env:
      - name: AWS_ACCESS_KEY_ID
        value: ***********
      - name: AWS_SECRET_ACCESS_KEY
        value: ***********
      args:
      - token
      - -i
      - im-demo
```
