### ISSUE TITLE
Race Condition in K8S Start

### ISSUE THREAD

**Issue by RaphaelHerd** [kubernetes-sigs/aws-iam-authenticator#31]
Hi,

I successfully tested the auth plugin follwing your instructions. Now I would like to automate the deployment. What I found out is, that currently I have a race condition between the DaemonSet and KubeApiServer.

While KubeApiServer is starting (after a new master instance is launched by the AWS Autoscaling Group), the KubeAPIServer is not able to find the kubeconfig.yaml. This is because it's not present on the machine. It's not because the DS is nor started before and therefore heptio auth was not able to generate the config file on the local disc of this machine.

Do you have any ideas how to solve this issue? Using K8s 1.7.10 and current version of Kops for installing.

Thx
Raphael

**Comment by bbck** [comment]
I just ran into this and got around it using `fileAssets` in kops to place a dummy file. You also need to edit the example deployment to drop the webhook configuration into `/srv/kubernetes` since it's mounted in the apiserver pod. 

```  yaml
fileAssets:
  - content: |
      clusters:
        - name: heptio-authenticator-aws
          cluster:
            certificate-authority: /srv/kubernetes/ca.crt
            server: https://127.0.0.1:21362/authenticate
      users:
        - name: apiserver
      current-context: webhook
      contexts:
      - name: webhook
        context:
          cluster: heptio-authenticator-aws
          user: apiserver
    name: heptio-authenticator-aws
    path: /srv/kubernetes/webhook-authentication.yaml
    roles:
    - Master
```
