### ISSUE TITLE
Support for session tags in aws-auth ConfigMap

### ISSUE THREAD

**Issue by parente** [kubernetes-sigs/aws-iam-authenticator#311]
Is there support for or interest in supporting the use of [AWS session tags](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html) in the aws-auth configmap? 

For example, I can allow users to assume an `okta-developer` role using Okta, while [mapping Okta attributes to session tags](https://www.okta.com/blog/2019/11/okta-and-aws-partner-to-simplify-access-via-session-tags/).  While I can't trust the Okta-defaulted session name when mapping the role to an EKS user:

```
mapRoles:
  - roleARN: arn:aws:iam::000000000000:role/okta-developer
    username: kubernetes-user-{{SessionName}}  # BAD: Users can pick a session name when assuming a role
    groups:
    - edit
```

I believe I would be able to trust the role session tags set by Okta which the user cannot modify:

```
mapRoles:
  - roleARN: arn:aws:iam::000000000000:role/okta-developer
    username: kubernetes-user-{{SessionTag.userName}} # OK: User cannot change session tags
    groups:
    - edit
```

I believe this feature would reduce the number of roles or user accounts needing to be created in IAM and mapped to unique users in kubernetes (e.g., when assigning users or teams a private k8s namespace).
