### ISSUE TITLE
Big typo in README.md which leads to error: "You must be logged in to the server (Unauthorized)"

### ISSUE THREAD

**Issue by alex-ferener** [kubernetes-sigs/aws-iam-authenticator#312]
I wanted to use kubectl with a different IAM role and edited the aws-auth ConfigMap. I've copy/pasted the example from README.md and received the error: "You must be logged in to the server (Unauthorized)"

Found it on EKS v1.14 platform version eks.8.

In `README.md` section "Full Configuration Format" > mapRoles > there is a **typo** in `roleARN`.

You need to write it lowercase: `rolearn`. After this change, the error is gone and kubectl is working.

```
 mapRoles: |
    - rolearn: arn:aws:iam::000_ID_000:role/custom-role
      username: custom-role
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::000_ID_000:role/eksctl-coms-dev-eks-nodegroup-com-NodeInstanceRole-H31D5NAU0QNJ0
      username: system:node:{{EC2PrivateDNSName}}
```

Please fix it everywhere you find it. (eg: deploy/example.yaml)

In Knowledge Center the example uses lowercase and everything works as expected -> https://aws.amazon.com/premiumsupport/knowledge-center/eks-api-server-unauthorized-error/
