### ISSUE TITLE
Token with expiry time longer than 1 hour ?

### ISSUE THREAD

**Issue by sfc-gh-pkrishnamurthy** [kubernetes-sigs/aws-iam-authenticator#316]
I use aws-iam-authenticator token -i <cluster_name> in a kube-config file to authenticate with EKS. The token's presigned url timeout causes my job to get 401s when performing any operation against the K8s api-server beyond 1 hr.

I periodically refresh the token by reloading the kube_conf file but that does not seem to help.

Is there a way to get a token with a longer presigned url timeout? If there isn't a way to configure the timeout, is there some way to programmatically refresh the token? My client submits a argo workflow and waits for its completion by polling on the status and I am unable to do so for a workflow running beyond 1 hour

Steps to reproduce the behavior
use
```
user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "k8s-1"
        - "k8s-1"
```       
in kube-conf have a client load the kube_config and a sample script like below

```
import time
from kubernetes import client as kubernetesClient
from kubernetes import config as kubernetesConfig
from kubernetes.client.rest import ApiException

kubernetesConfig.load_kube_config(config_file=<path/to/kubeConfFile>)
kubeClient = kubernetesClient.CoreV1Api()
namespace = kube-system

while i < 61:
     try:
          api_response = kubeClient.list_namespaced_pod(namespace)
     except ApiException as e:
          if e.status == 401:
               print("This is the failure in question")
          raise e
     time.sleep(60)
```
When the script is executed one would observe that you get 401 errors after the 1 hour mark

expected result: More of a question on how to get a token with a longer expiry ?
