### ISSUE TITLE
kubeconfig missing user section

### ISSUE THREAD

**Issue by PercleChiu** [kubernetes-sigs/aws-iam-authenticator#325]
i'm using aws-iam-authenticator 4.0 with kubeadm (for some reason 5.0 hangs on me ... )

when it (4.0) starts, it generates cert, pem, and kubeconfig as expect. However, kubeconfig users section looks like 
```
users:
  - name: apiserver
``` 
it doesn't work because api server gets x.509 error when sending request to aws-iam-authenticator

i had to manually add user cert / key location for it to work. 
```
users:
  - name: apiserver
    user:
      client-certificate: /var/aws-iam-authenticator/cert.pem
      client-key: /var/aws-iam-authenticator/key.pem
```

Also, the documentation here doesn't mention mounting key pair into kube-apiserver pod.. it took me a while to figure that out.
