### ISSUE TITLE
IAM assumed roles don't work with EKSConfigMap

### ISSUE THREAD

**Issue by ayberk** [kubernetes-sigs/aws-iam-authenticator#328]
I expect following to work with `EKSConfigMap` as it works with the `MountedFile` backend:

```
  mapUsers: |
    - userarn: arn:aws:sts::99999999:assumed-role/ReadOnly/foobar
      username: kubernetes-admin
      groups:
        - system:masters
```

However, it ends up being not mapped correctly and the role can't access to the cluster.

Providing the role ARN directly instead works: 
```
  mapUsers: |
    - userarn: arn:aws:iam::99999999:role/ReadOnly
      username: kubernetes-admin
      groups:
        - system:masters
```

The problem seems to be [Canonicalize](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/8875022195cffe6c0d37054ecd7080315ed7ff2f/pkg/arn/arn.go#L20) not being called for the mappings defined in the config map.

**Comment by epaaso** [comment]
Cheers!
I was under the wrong impression that this next snippet would work for authenticating IAM users assuming a role:

```yaml
mapRoles: |
    - rolearn: arn:aws:iam::99999999:role/ReadOnly
      username: kubernetes-admin
      groups:
        - system:masters
```

Instead it only works if I write it under `mapUsers`. I am using kubectl 18.1 and kubernetes 1.16 cluster. My aws cli is v2.
