### ISSUE TITLE
Access denied on K8S v1.15.2

### ISSUE THREAD

**Issue by giacomolicari** [kubernetes-sigs/aws-iam-authenticator#357]
When we migrated our K8S cluster from v1.14.10 to v1.15.2 , using KOPS 1.17.1, we noticed **aws-iam-authenticator** started erroring.
In particular it got access denied to files in `/var/aws-iam-authenticator` and `/etc/kubernetes/aws-iam-authenticator`.

To fix the issue, we first upgraded aws-iam-authenticator from v0.4.0 to v0.5.2, then we saw the issue was still there, so finally the trick was to set an initContainer to fix permissions at startup:

```
initContainers:
  - name: fix-perms
    image: busybox
    command: ['sh', '-c', 'chown 10000:10000 /var/aws-iam-authenticator; chown 10000:10000 /etc/kubernetes/aws-iam-authenticator; chmod -R 755 /var/aws-iam-authenticator/']
    volumeMounts:
    - name: state
      mountPath: /var/aws-iam-authenticator/
    - name: output
      mountPath: /etc/kubernetes/aws-iam-authenticator/
```

For reference, master nodes are running on a Debian image: `kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-11-19`

Hope this helps!
