### ISSUE TITLE
how to visit aws eks with client certificate

### ISSUE THREAD

**Issue by rootdeep** [kubernetes-sigs/aws-iam-authenticator#420]
1. make a csr to cluster by admin user, 
2. aprove it manully with kubectl cmd 
3. grant the user in certificate  (e.g. roc)  an admin cluster role 
4. make a kubeconfig with key and cert , the root ca in kubeconfig  is coppyed from eks 
    console 

 ```
apiVersion: v1
clusters:
  - cluster:
        certificate-authority-data: xxxx
        server: https://xxx.eks.amazonaws.com
    name: arn:aws:eks:xxx:cluster/clustername
contexts:
  - context:
        cluster: arn:aws:eks:xxx:cluster/clustername
        user:  roc
    name: default
current-context: default
kind: Config
preferences: {}
users:
  - name: roc
    user:
       client-certificate-data: xxx
       client-key-data: xxx
   ```
5. visit cluster resource with that kubeconfig 
6. output is  
    error: You must be logged in to the server (Unauthorized)
