### ISSUE TITLE
SSO role mapping issue

### ISSUE THREAD

**Issue by malcolm061990** [kubernetes-sigs/aws-iam-authenticator#436]
Hi.
We have EKS - 1.20.
We have one SSO role that is used by two different users: 
-`user1` - admin (me)
-`user2` must have admin access only in specific namespace.
```yaml
# part of aws-auth configmap. Same rolearn for 2 different usernames
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::222222222222:role/AWSReservedSSO_Permission_AdminFullAccess_8a2319305372f153
      username: user1
    - groups:
      - sd:developers
      rolearn: arn:aws:iam::222222222222:role/AWSReservedSSO_Permission_AdminFullAccess_8a2319305372f153
      username: user2

# role binding for sd:developers group used in aws-auth configmap above
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dns-firewall-dev
  name: sd:developers-dns-firewall-dev-admin
subjects:
- kind: Group
  name: sd:developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
```

Under `user1` I added the `user2` to `aws-auth` configmap and I am getting the issue:
```bash
kubectl -n kube-system edit cm aws-auth
Error from server (Forbidden): configmaps "aws-auth" is forbidden: User "user2" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
```
But I am not `user2`, I am `user1`. Why does my shell start use another user?

If I remove the `user2` from `aws-auth` configmap under other admin user (that doesn't use SSO), my `user1` starts working.

The question is: 
how can I configure `aws-auth` to use single SSO role for different users with different permissions?

**Comment by loganmzz** [comment]
You have two bindings for the same IAM Role `arn:aws:iam::222222222222:role/AWSReservedSSO_Permission_AdminFullAccess_11111111111111`. I suppose the last found is the one which is applied by authn, thus you're K8S identity is:

```yaml
username: user2
groups:
- sd:developers
```
