### ISSUE TITLE
why service account token  works with kubectl ,  but bootstraptoken does not work

### ISSUE THREAD

**Issue by rootdeep** [kubernetes-sigs/aws-iam-authenticator#441]
I tried to use service account token and bootstrap token to build a kubeconfig to visit aws eks cluster. The result is:  service account token works, but bootstraptoken doesn't work.  The steps as follow:

1. create serviceaccount and bootstrap token on a aws eks cluster, both sa token and bootstraptoken have 
   admin  rbac role .

yaml file for genereating service account token
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-cr
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: test
    namespace: default
```

yaml file for bootstrap token

```
apiVersion: v1
kind: Secret
metadata:
  name: bootstrap-token-07401b
  namespace: kube-system
type: bootstrap.kubernetes.io/token
stringData:
  token-id: 07401b
  token-secret: f395accd246ae52d
  expiration: 2025-05-10T03:22:11Z
  usage-bootstrap-authentication: "true"
  usage-bootstrap-signing: "true"
  auth-extra-groups: system:bootstrappers:test:client

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bootstrapping-test
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bootstrapping-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bootstrapping-test
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:bootstrappers:test:client
```

2. use sa token and bootstrap token the make a kubeconfig 
   cat  kubeconfig-sa-token

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:  ${base64-encode-string}
    server: https://xxxx.us-east-2.eks.amazonaws.com
  name: test
contexts:
- context:
    cluster: test
    user: "100014587656"
  name: default
current-context: test-100014587656-default
kind: Config
preferences: {}
users:
- name: "100014587656"
  user:
    token:  ${base64-decode-sa-token} 
```
3. replace the decoded sa token with bootstrap token "07401b.f395accd246ae52d" (created before), and save 
   as another  file named config-bootstraptoken

4. run kubectl get pods --kubeconfig=config-sa-token  
    this command works, it will return pods list in default namespace 
5. run kubectl get pods --kubeconfig=config-bootstraptoken
    it not works , error is :    ***error: You must be logged in to the server (Unauthorized)***

I am confused why sa token can be authenticated ,but bootstrap token can not  be. 
I want to know the reason for both cases. 
Thanks!
