### ISSUE TITLE
Can I run 'aws-iam-authenticator server' on non-ec2 environment?

### ISSUE THREAD

**Issue by Uanid** [kubernetes-sigs/aws-iam-authenticator#486]
I want run this server on non-ec2 environment(ex: Azure VM) for users can login with AWS IAM identity. But seems it requires EC2 IMDS apiserver.

Is there any option run this on non-ec2 environment?

**Comment by matskiv** [comment]
It worked for me when I added the region env var, e.g:
```
      containers:
      - name: aws-iam-authenticator
        env:
          - name: "AWS_REGION"
            value: "us-east-1"
``` 
btw, the "global" region works too, because this is used for STS calls. The nuances are documented - [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html).
