### ISSUE TITLE
using gcp auth-provider for kubecfg

### ISSUE THREAD

**Issue by sp-joseluis-ledesma** [kubernetes-sigs/aws-iam-authenticator#56]
Hi!
  first of all congratulations for this application :). I have been playing with it, and  found it is a lot easier to configure the heptio-authenticator-aws in kubecfg with the gcp auth provider. As the current output from the command is not a json, it must be wrapped to work, but more or less it is something like:

haawrapper.sh:
```
#!/bin/sh
token=`heptio-authenticator-aws token -i CLUSTERID -r ROLEARN`
if [ $? -ne 0 ]; then
  exit 1
fi
echo "{\"token\": \"$token\", \"expire\": \"$(TZ=Z date --date "now + 15 minutes" +"%Y-%m-%dT%H:%M:%SZ")\"}"
```

then you can configure in kubecfg the user as follows:

```
- name: kubernetes-admin
  user:
    auth-provider:
      config:
        cmd-path: /path/to/haawrapper.sh
        expiry-key: '{.expire}'
        token-key: '{.token}'
      name: gcp
```

and for now on you can run kubectl and it will just works. I don't know if you didn't think on this possibility, or you find it a nasty hack.
