### ISSUE TITLE
[Feature request]: Role access based on session name

### ISSUE THREAD

**Issue by mdhwk** [kubernetes-sigs/aws-iam-authenticator#605]
### What would you like to be added?

Hi,
Not sure if a similar request have been made before but anyway here we go.

I would like to have the ability to allow a role based on session name.
Currently, AFAIK, you can only do the following 
```
- rolearn: arn:aws:iam:000000000:role/All_Engineers
  groups:
    - "SUPER_ADMIN_NS_1"
```
which would result in everyone that can assume that role gets the `SUPER_ADMIN_NS_1` permissions and therefor access to that namespace.

What I would like to have would be something like 
```
- rolearn: arn:aws:iam:000000000:role/NS_1_Access
  allowedSessionNames: 
    - "billy.bob@mycorp.com"
  groups:
    - "SUPER_ADMIN_NS_1"
```
This would provide the possibility of providing fine grained access inside an namespace.

Maybe people already have solved this in some other way and if so I would be happy to hear how :) 
And if not, happy to help implement it, if it comes to that.

// Martin

### Why is this needed?

To use one role for eg. engineering and still be able to give fine grained access to users of that role.

### Anything else we need to know?

See this [doc](https://aws.amazon.com/blogs/security/easily-control-naming-individual-iam-role-sessions) for more info on enforcing the session name to remove user override possibilities.
