### ISSUE TITLE
KOPS exec hook fails to set file permissions on kubeconfig - daemonset crashes.

### ISSUE THREAD

**Issue by innovia** [kubernetes-sigs/aws-iam-authenticator#90]
After setting up KOPS cluster config to include the systemd hook for copying the files the pod is crashing on permission denied when attempting to write to the kubeconfig file

```time="2018-06-07T11:27:16Z" level=fatal msg="could not write kubeconfig" error="open /etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml: permission denied" kubeconfigPath=/etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml```

The issues are:
1) file permissions is not preserved on S3 after copied to disk
2) systemd one shot type exit after the cp so any command after the aws s3 cp will not run

**Comment by christopherhein** [comment]
@innovia I'm not sure your setup is correct, the log shouldn't have a permission error on writing the files if you are pulling them from S3, check your `volumeMounts` the directions on the `README.md` and the `example.yaml` have subtle differences to account for the file system permissions.

**Comment by christopherhein** [comment]
> 4. Update the Authenticator DaemonSet's state and output volumes to both use /srv/kubernetes/heptio-authenticator-aws/ for their hostPaths.

**Comment by christopherhein** [comment]
check the full walk through - https://aws.amazon.com/blogs/opensource/deploying-heptio-authenticator-kops/ and compare

**Comment by innovia** [comment]
@christopherhein 
i did followed your blog pos exactly.

as you can see from my config below both output and state mapped to `/srv/kubernetes/heptio-authenticator-aws`

it makes sense that there will be a permissions issue since when copying files from S3 they don't preserve the state and by default become rw-r-r

now any pod trying to read these file is considered as other in the ocatl permissions (it's not the owner nor does it belong to a group on the container os host).

Am i missing something?

here's my config
```
# authenticator.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: heptio-authenticator-aws
  labels:
    k8s-app: heptio-authenticator-aws
data:
  config.yaml: |
    clusterID: some.domain.com
    server:
      mapRoles:
      - roleARN: arn:aws:iam::1234567812:role/KubernetesAdmin
        username: kubernetes-admin
        groups:
        - system:masters

      - roleARN: arn:aws:iam::1234567812:role/KubernetesDevUsersGroup
        username: dude
        groups:
        - dev-users


---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: heptio-authenticator-aws
  labels:
    k8s-app: heptio-authenticator-aws
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        k8s-app: heptio-authenticator-aws
    spec:
      # run on the host network (don't depend on CNI)
      hostNetwork: true

      # run on each master node
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists

      # run `heptio-authenticator-aws server` with three volumes
      # - config (mounted from the ConfigMap at /etc/heptio-authenticator-aws/config.yaml)
      # - state (persisted TLS certificate and keys, mounted from the host)
      # - output (output kubeconfig to plug into your apiserver configuration, mounted from the host)
      containers:
      - name: heptio-authenticator-aws
        image: gcr.io/heptio-images/authenticator:v0.3.0
        args:
        - server
        - --config=/etc/heptio-authenticator-aws/config.yaml
        - --state-dir=/var/heptio-authenticator-aws
        - --generate-kubeconfig=/etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml

        resources:
          requests:
            memory: 20Mi
            cpu: 10m
          limits:
            memory: 20Mi
            cpu: 100m

        volumeMounts:
        - name: config
          mountPath: /etc/heptio-authenticator-aws/
        - name: state
          mountPath: /var/heptio-authenticator-aws/
        - name: output
          mountPath: /etc/kubernetes/heptio-authenticator-aws/
      volumes:
      - name: config
        configMap:
          name: heptio-authenticator-aws
      - name: output
        hostPath:
          path: /srv/kubernetes/heptio-authenticator-aws/
      - name: state
        hostPath:
          path: /srv/kubernetes/heptio-authenticator-aws/
```

**Comment by christopherhein** [comment]
And just to be absolutely clear in the kops hook you are `s3 cp`'ing them into that `/srv` directory? If the setup was done correctly we shouldn't need to write to that directory ever. 

The idea here is to generate the files locally and push them to S3 so that in an HA multi-master kops deployment that they're able to all use the same exact key pair and `kubeconfig`. If you ssh into the master and `ls` that directory where they there before? Can you check the logs for `kops-hook-authenticator-config.service` from systemd

**Comment by kaspernissen** [comment]
I encountered the same error when trying to upgrade from `0.1.0` to `0.3.0` with a Kops cluster. Everything works fine with `kops 1.8.1` and `kubernetes 1.8.10` using `kubectl (1.10)`. 

Upgraded my local client with:
```
wget https://github.com/heptio/authenticator/releases/download/v0.3.0/heptio-authenticator-aws_0.3.0_darwin_amd64
mv heptio-authenticator-aws_0.3.0_darwin_amd64 /usr/local/bin/heptio-authenticator-aws
chmod +x /usr/local/bin/heptio-authenticator-aws
```

With a `0.3.0` client and server `0.1.0` everything seems to we working fine. However, when updating the server, by changing the image to:
```
      image: gcr.io/heptio-images/authenticator:v0.3.0
```
... and then applying this in the cluster, the heptio-authenticator server outputs the following fatal log:
```
time="2018-06-11T11:15:17Z" level=info msg="loaded existing keypair" certPath=/var/heptio-authenticator-aws/cert.pem keyPath=/var/heptio-authenticator-aws/key.pem
time="2018-06-11T11:15:17Z" level=info msg="writing webhook kubeconfig file" kubeconfigPath=/etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml
time="2018-06-11T11:15:17Z" level=fatal msg="could not write kubeconfig" error="open /etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml: permission denied" kubeconfigPath=/etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml
``` 

daemon-set
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: heptio-authenticator-aws
  labels:
    k8s-app: heptio-authenticator-aws
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        k8s-app: heptio-authenticator-aws
    spec:
      hostNetwork: true

      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists

      containers:
      - name: heptio-authenticator-aws
        image: gcr.io/heptio-images/authenticator:v0.1.0
        args:
        - server
        - --config=/etc/heptio-authenticator-aws/config.yaml
        - --state-dir=/var/heptio-authenticator-aws
        - --generate-kubeconfig=/etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml

        resources:
          requests:
            memory: 20Mi
            cpu: 10m
          limits:
            memory: 20Mi
            cpu: 100m

        volumeMounts:
        - name: config
          mountPath: /etc/heptio-authenticator-aws/
        - name: state
          mountPath: /var/heptio-authenticator-aws/
        - name: output
          mountPath: /etc/kubernetes/heptio-authenticator-aws/

      volumes:
      - name: config
        configMap:
          name: heptio-authenticator-aws
      - name: output
        hostPath:
          path: /srv/kubernetes/heptio-authenticator-aws/
      - name: state
        hostPath:
          path: /srv/kubernetes/heptio-authenticator-aws/
```

configMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: heptio-authenticator-aws
  labels:
    k8s-app: heptio-authenticator-aws
data:
  config.yaml: |
    clusterID: k8s.dev.example.com
    server:

      mapRoles:
      - roleARN: arn:aws:iam::<ACCOUNT_ID>:role/KubernetesAdmin
        username: "kubernetes-admin:{{SessionName}}"
        groups:
        - aws:kubernetes:admin

      - roleARN: arn:aws:iam::<ACCOUNT_ID>:role/KubernetesDev
        username: "kubernetes-dev:{{SessionName}}"
        groups:
        - aws:kubernetes:dev

      - roleARN: arn:aws:iam::<ACCOUNT_ID>:role/KubernetesView
        username: "kubernetes-view::{{SessionName}}"
        groups:
        - aws:kubernetes:view

      - roleARN: arn:aws:iam::<ACCOUNT_ID>:role/KubernetesCD
        username: "kubernetes-cd::{{SessionName}}"
        groups:
        - aws:kubernetes:cd

      mapAccounts:
      - "<ACCOUNT_ID>"
```

**Comment by andyrhee** [comment]
I also encountered the same issue after upgrading the server version from v0.1.0 to v0.3.0.  Fixed the issue by changing the server config in the DaemonSet to use ```--kubeconfig-pregenerated=true``` instead of ```--generate-kubeconfig=/etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml```.

The ```--kubeconfig-pregenerated``` option is newly available option with v0.3.0 which actually should be used when you want to use pregenerated kubconfig file.  This is what's missing with v0.1.0 in addition to mapAccounts mappings.

**Comment by kaspernissen** [comment]
Thank you @andyrhee. Totally missed that.

**Comment by innovia** [comment]
@christopherhein who do you recommend continuing / changing  the PR ?

**Comment by arthur-c** [comment]
I had the same issue. I added `--kubeconfig-pregenerated=true` but it was not enough.

I opened permission via kops-hook-authenticator-config.service

```
      ExecStart=/bin/chmod -R 0777 /srv/kubernetes/heptio-authenticator-aws
```

and it's now ok

**Comment by roffe** [comment]
the example in the updated docs from the PR solved my daemonset crash looping a swell

Kops 1.9.1, k8s 1.9.6 authenticator 0.3.0

**Comment by arthur-c** [comment]
@roffe I first tried that (removing --generate-kubeconfig and adding --kubeconfig-pregenerated) but didn't work, I had to keep both flags

**Comment by roffe** [comment]
@arthur-c what about file permissions, could that part be omnited from the systemd unit when using both flags?

**Comment by Raffo** [comment]
Can anyone here summarize what are the combinations of things that made it work? I'm facing the sam e issue with kops 1.9.1, authenticator 0.3.0.

**Comment by christopherhein** [comment]
I started digging into this yesterday.

For me, I set up using the blog changed the image ID to `0.3.0` and ran into the same issue as above; to solve it, I verified that the files existed on the node from the pre-kubelet hook, which they did so permissions weren't an issue from that side. Then I changed the `--generate-kubeconfig` to just `--kubeconfig-pregenerated` and it worked as expected. I didn't validate w/ Kops 1.8 yet, but it should work the same.

**Comment by niallmccullagh** [comment]
Same issue as @arthur-c in that the authenticator pod is trying to write new cert and key. Should it should be using the cert and key downloaded from S3?

Authenticator Pod log:
```
$ kubectl -n kube-system log heptio-authenticator-aws-jbhnf
time="2018-07-11T23:31:08Z" level=info msg="mapping IAM role" groups="[system:masters]" role="arn:aws:iam::XXXX:role/KubernetesAdmin" username=kubernetes-admin
time="2018-07-11T23:31:15Z" level=info msg="generated a new private key and certificate" certBytes=810 keyBytes=1192
time="2018-07-11T23:31:15Z" level=info msg="saving new key and certificate" certPath=/var/heptio-authenticator-aws/cert.pem keyPath=/var/heptio-authenticator-aws/key.pem
time="2018-07-11T23:31:15Z" level=fatal msg="could not load/generate a certificate" error="open /var/heptio-authenticator-aws/cert.pem: permission denied"
```


Daemonset config:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: heptio-authenticator-aws
  labels:
    k8s-app: heptio-authenticator-aws
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        k8s-app: heptio-authenticator-aws
    spec:
      # run on the host network (don't depend on CNI)
      hostNetwork: true

      # run on each master node
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists

      # run `heptio-authenticator-aws server` with three volumes
      # - config (mounted from the ConfigMap at /etc/heptio-authenticator-aws/config.yaml)
      # - state (persisted TLS certificate and keys, mounted from the host)
      # - output (output kubeconfig to plug into your apiserver configuration, mounted from the host)
      containers:
      - name: heptio-authenticator-aws
        image: gcr.io/heptio-images/authenticator:v0.3.0
        args:
        - server
        - --config=/etc/heptio-authenticator-aws/config.yaml
        - --state-dir=/var/heptio-authenticator-aws
        - --kubeconfig-pregenerated

        resources:
          requests:
            memory: 20Mi
            cpu: 10m
          limits:
            memory: 20Mi
            cpu: 100m

        volumeMounts:
        - name: config
          mountPath: /etc/heptio-authenticator-aws/
        - name: state
          mountPath: /var/heptio-authenticator-aws/
        - name: output
          mountPath: /etc/kubernetes/heptio-authenticator-aws/
      volumes:
      - name: config
        configMap:
          name: heptio-authenticator-aws
      - name: output
        hostPath:
          path: /srv/kubernetes/heptio-authenticator-aws/
      - name: state
        hostPath:
          path: /srv/kubernetes/heptio-authenticator-aws/
```

Host file permissions:
```
ls -al /srv/kubernetes/aws-iam-authenticator/
total 20
drwxr-xr-x 2 root root 4096 Jul 11 22:35 .
drwxr-xr-x 5 root root 4096 Jul 11 22:59 ..
-rw-r--r-- 1 root root 1151 Jul 11 22:11 cert.pem
-rw-r--r-- 1 root root 1675 Jul 11 22:11 key.pem
-rw-r--r-- 1 root root 2046 Jul 11 22:12 kubeconfig.yaml
```
